//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "642079272986c03b2f3ecd38"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test Testsson",
  "email": "test@mail.com",
  "password": "test"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "test"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/642079f32986c03b2f3ecd3d

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

[{
  "name": "Largeleaf Geigertree",
  "description": "Aenean fermentum.",
  "price": 349,
  "lager": 10
}, {
  "name": "Wormskjold's Aplodon Moss",
  "description": "Donec ut mauris eget massa tempor convallis.",
  "price": 330,
  "lager": 6
}, {
  "name": "Salmon River Beardtongue",
  "description": "Morbi non quam nec dui luctus rutrum.",
  "price": 160,
  "lager": 3
}, {
  "name": "Albizia",
  "description": "Nam dui.",
  "price": 244,
  "lager": 11
}, {
  "name": "Pamohe",
  "description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
  "price": 351,
  "lager": 5
}, {
  "name": "Russian Wheatgrass",
  "description": "Cras non velit nec nisi vulputate nonummy.",
  "price": 476,
  "lager": 3
}, {
  "name": "Lake Huron Tansy",
  "description": "Nulla suscipit ligula in lacus.",
  "price": 325,
  "lager": 7
}, {
  "name": "Floating Primrose-willow",
  "description": "Morbi a ipsum.",
  "price": 109,
  "lager": 9
}, {
  "name": "Gama Medic",
  "description": "In quis justo.",
  "price": 346,
  "lager": 3
}, {
  "name": "Japanese Goose Neck Moss",
  "description": "Maecenas ut massa quis augue luctus tincidunt.",
  "price": 403,
  "lager": 6
}]

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "642079272986c03b2f3ecd38",
      "products": [
    {
      "productId": "642079f32986c03b2f3ecd3f",
      "quantity": 1
    },
    {
      "productId": "642079f32986c03b2f3ecd40",
      "quantity": 2
    }
  ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###